apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-namespaces.yaml
- 01-fw-prompt.yaml
- 02-app-chatbot.yaml
- 03-fw-model.yaml
- 04-ctrl-prompt-llm-guard.yaml
- 05-ctrl-prompt.yaml
- 06-pvcs.yaml
components:
# - ./netpols/