apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-namespaces.yaml
- 01-fw-prompt.yaml
- 02-app-chatbot.yaml
- 03-fw-model.yaml
- 04-ctrl-prompt-llm-guard.yaml
- 05-ctrl-prompt.yaml
- 06-pvcs.yaml
components:
# - ./netpols/
images:
# our images
- name: proxy-llm-guard
  newName: ghcr.io/stealthybox/ai-security-architecture/proxy-llm-guard
  newTag: v0.0.1
- name: proxy-chatbot
  newName: ghcr.io/stealthybox/ai-security-architecture/proxy-chatbot
  newTag: v0.0.1
# dependencies
- name: laiyer/llm-guard-api
  newTag: 0.3.15
