apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: fw-prompt-policy
  namespace: fw-prompt
specs:
  - endpointSelector:
      matchLabels: {}
    ingress:
      - fromEntities:
          - all
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": app-chatbot
  - endpointSelector:
      matchLabels: {}
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
  - endpointSelector:
      matchLabels: {}
    ingress:
      - fromEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": ctrl-prompt
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": ctrl-prompt
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: chatbot-policy
  namespace: app-chatbot
specs:
  - endpointSelector:
      matchLabels: {}
    ingress:
      - fromEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": fw-prompt
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": fw-model
  - endpointSelector:
      matchLabels: {}
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: fw-model-policy
  namespace: fw-model
specs:
  - endpointSelector:
      matchLabels: {}
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
  - endpointSelector:
      matchLabels: {}
    ingress:
      - fromEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": app-chatbot
    egress:
      - toEntities:
          - all
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: ctrl-prompt-policy
  namespace: ctrl-prompt
specs:
  - endpointSelector:
      matchLabels: {}
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": kube-system
              "k8s:k8s-app": kube-dns
  - endpointSelector:
      matchLabels: {}
    ingress:
      - fromEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": fw-prompt
    egress:
      - toEndpoints:
          - matchLabels:
              "k8s:io.kubernetes.pod.namespace": fw-prompt
  - endpointSelector:
      matchLabels: {}
    egress:
      - toFQDNs:
          - matchName: "huggingface.co"
